Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -10,11 +10,11 @@ phases:
       - echo Building the Docker image...
       - echo Logging in to Docker Hub
       - docker login -u sbpraonalla -p $DOCKER_HUB_TOKEN
-      - echo ${CUSTOMER_NAME}
+      - echo ${PROJECT_NAME}
       - >
-        REPO_EXISTS=$(aws ecr describe-repositories --repository-names ${CUSTOMER_NAME} --region ${AWS_REGION} 2>&1 || echo "not found");
+        REPO_EXISTS=$(aws ecr describe-repositories --repository-names ${PROJECT_NAME} --region ${AWS_REGION} 2>&1 || echo "not found");
         if [[ $REPO_EXISTS == *"not found"* ]]; then
-          aws ecr create-repository --repository-name ${CUSTOMER_NAME} --region ${AWS_REGION}
+          aws ecr create-repository --repository-name ${PROJECT_NAME} --region ${AWS_REGION}
         fi
   build:
     commands:
@@ -22,5 +22,5 @@ phases:
   post_build:
     commands:
       - echo Pushing the Docker image to ECR...
-      - docker tag ${CUSTOMER_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${CUSTOMER_NAME}:${TAG_NAME}
-      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${CUSTOMER_NAME}:${TAG_NAME}
+      - docker tag ${PROJECT_NAME}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}:${TAG_NAME}
+      - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}:${TAG_NAME}
